### ISSUE TITLE
Building fails on Windows

### ISSUE THREAD

**Issue by yhdanid** [DavZim/RITCH#1]
Looking into the scr directory I see object files and the .so package. This could be the source of the problem. The session was as follows:

> devtools::install_github("DavZim/RITCH")
Downloading GitHub repo DavZim/RITCH@master
from URL https://api.github.com/repos/DavZim/RITCH/zipball/master
Installing RITCH
Installing 1 package: data.table
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/data.table_1.10.4-3.zip'
Content type 'application/zip' length 1507088 bytes (1.4 MB)
downloaded 1.4 MB

package ‘data.table’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        E:\Users\dani\AppData\Local\Temp\RtmpOYHIbb\downloaded_packages
Installing 1 package: R.utils
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/R.utils_2.6.0.zip'
Content type 'application/zip' length 990396 bytes (967 KB)
downloaded 967 KB

package ‘R.utils’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        E:\Users\dani\AppData\Local\Temp\RtmpOYHIbb\downloaded_packages
Installing 1 package: Rcpp
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/Rcpp_0.12.14.zip'
Content type 'application/zip' length 4345251 bytes (4.1 MB)
downloaded 4.1 MB

package ‘Rcpp’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        E:\Users\dani\AppData\Local\Temp\RtmpOYHIbb\downloaded_packages
"E:/dev/R/R-3.3.1/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  "E:/Users/dani/AppData/Local/Temp/RtmpOYHIbb/devtools5668586b30e9/DavZim-RITCH-4c79183"  \
  --library="E:/dev/R/R-3.3.1/library" --install-tests 

* installing *source* package 'RITCH' ...
** libs

*** arch - i386
E:\dev\Rtools\mingw_32\bin\nm.exe: MessageTypes.o: File format not recognized
E:\dev\Rtools\mingw_32\bin\nm.exe: RITCH.o: File format not recognized
E:\dev\Rtools\mingw_32\bin\nm.exe: RcppExports.o: File format not recognized
E:\dev\Rtools\mingw_32\bin\nm.exe: countMessages.o: File format not recognized
E:\dev\Rtools\mingw_32\bin\nm.exe: getMessageCountDF.o: File format not recognized
E:\dev\Rtools\mingw_32\bin\nm.exe: getMessages.o: File format not recognized
E:/dev/Rtools/mingw_32/bin/g++ -shared -s -static-libgcc -o RITCH.dll tmp.def MessageTypes.o RITCH.o RcppExports.o countMessages.o getMessageCountDF.o getMessages.o -Ld:/Compiler/gcc-4.9.3/local330/lib/i386 -Ld:/Compiler/gcc-4.9.3/local330/lib -LE:/dev/R/R-33~1.1/bin/i386 -lR
MessageTypes.o: file not recognized: File format not recognized
collect2.exe: error: ld returned 1 exit status
no DLL was created
ERROR: compilation failed for package 'RITCH'
* removing 'E:/dev/R/R-3.3.1/library/RITCH'
Installation failed: Command failed (1)

**Comment by DavZim** [comment]
Good catch and thanks for notifying. I have updated the repo (excluded .o and .so from my Linux built), now on a fresh install it compiles the libraries. Can you give it a try again?

**Comment by yhdanid** [comment]
It builds fine now. Thumbs up for quick response.

**Comment by DavZim** [comment]
closed with 4c79183
