### ISSUE TITLE
VWAP

### ISSUE THREAD

**Issue by volare2016** [DavZim/RITCH#12]
Hi David, 

I've found the RITCH extremely helpful. I wonder if there's a function to calculate the running volume-weighted average price (VWAP) for each stock at every trading hour including the market close. Thanks!

Eric

**Comment by DavZim** [comment]
Hi Eric,
glad you find RITCH helpful. The scope of the library is (currently) only to parse the data into a data.table, all kinds of other data operations can usually be done using `data.table` or some kinds of other data.frame library.
I imagine, in your case you would have to calculate the hours of the nanosecond-timestamps and then group-by and summarise the trade-messages for price and volume.
Hope that helps.
Best,
David

**Comment by volare2016** [comment]
Thank you for your quick reply, David. It’s very helpful. 

Eric
