### ISSUE TITLE
Error in running: file <- "01302019.NASDAQ_ITCH50" msg_count <- count_messages(file,add_meta_data = TRUE)

### ISSUE THREAD

**Issue by puneetkumar1997** [DavZim/RITCH#13]

**Comment by puneetkumar1997** [comment]
[Counting]   Error in RITCH:::getMessageCountDF(file, buffer_size, quiet) : 
  File Error!

**Comment by DavZim** [comment]
Sorry for coming back so late, is this still active, if so, have a look at the file name. Your format is `MMDDYYY.NASDAQ_ITCH50`, afaik NASDAQ provides the data in the form YYYYMMDD.NASDAQ_ITCH50.
