### ISSUE TITLE
have issue installing on Mac OS X catalina

### ISSUE THREAD

**Issue by ssh352** [DavZim/RITCH#23]
<img width="792" alt="Screen Shot 2020-09-02 at 5 25 27 PM" src="https://user-images.githubusercontent.com/41779116/91964102-500e6800-ed41-11ea-9020-82ba0636f24a.png">
Thanks for such a useful package! I have some issue installing the package via devtools.

<img width="1280" alt="Screen Shot 2020-09-02 at 5 23 15 PM" src="https://user-images.githubusercontent.com/41779116/91963911-163d6180-ed41-11ea-8189-ba4766c1caac.png">

**Comment by ssh352** [comment]
update: install success on ubuntu 18.04

**Comment by DavZim** [comment]
Hi ssh352. 
Happy that you find the package helpful.
Can you make sure that you have the latest version of Rcpp installed.
The error does not seem to originate in the Ritch package but from code imported from Rcpp.

**Comment by ssh352** [comment]
Rcpp is the latest version.
<img width="649" alt="Screen Shot 2020-09-03 at 9 17 17 AM" src="https://user-images.githubusercontent.com/41779116/92060423-4844d700-edc6-11ea-938d-f43d7c4eb6eb.png">

I've also tried installing on Mac Mojave  and it succeeded. So it only failed on my Mac Catalina so far.

**Comment by DavZim** [comment]
Hmm, not really sure what triggers this error, an you maybe check what kind of tooling is installed, i.e., `gcc --version`

**Comment by ssh352** [comment]
on macOS catalina
<img width="418" alt="Screen Shot 2020-09-04 at 9 31 17 AM" src="https://user-images.githubusercontent.com/41779116/92189517-69bec500-ee91-11ea-84d6-22297b8b5d73.png">

found a related thread on using the cmath header with the catalina
 https://stackoverflow.com/questions/58628377/catalina-c-using-cmath-headers-yield-error-no-member-named-signbit-in-th

**Comment by DavZim** [comment]
Were you able to solve the problem?

**Comment by ssh352** [comment]
No, I think it is a Catalina specific issue and I switch to use the Linux package instead.
