### ISSUE TITLE
Can't read NASDAQ ITCH File

### ISSUE THREAD

**Issue by ChrisPetersen1098** [DavZim/RITCH#28]
I've installed RITCH and can read and parse the file that comes with the package.  I have downloaded a sample ITCH file from "ftp://emi.nasdaq.com/ITCH/Nasdaq%20ITCH/" and choose 07302019.NASDAQ_ITCH50.  I downloaded the 3.5gb file, unzipped it.  When I call any functions from this file, it parses blank tables, like the file is empty.  

I have also downloaded 20191030.BX_ITCH_50 and can parse these messages.  Is there a reason why BX files work and NASDAQ files don't?  Am I doing something wrong?

**Comment by DavZim** [comment]
That is not intended. Can you post the output of `count_messages(file)`, `read_orders(file)`, `get_exchange_from_filename(file)`, and `get_date_from_filename(file)` where `file` is the NASDAQ file.

**Comment by ChrisPetersen1098** [comment]
Sure....
> count_messages(file)
[Counting]   0 total messages found
[Converting] to data.table
[Done]       in 0.00 secs at 8.65TB/s
    msg_type count
 1:        S     0
 2:        R     0
 3:        H     0
 4:        Y     0
 5:        L     0
 6:        V     0
 7:        W     0
 8:        K     0
 9:        J     0
10:        h     0
11:        A     0
12:        F     0
13:        E     0
14:        C     0
15:        X     0
16:        D     0
17:        U     0
18:        P     0
19:        Q     0
20:        B     0
21:        I     0
22:        N     0
    msg_type count


> read_orders(file)
[Counting]   num messages 0
[Converting] to data.table
[Done]       in 0.11 secs at 76.24GB/s
Empty data.table (0 rows and 13 cols): msg_type,stock_locate,tracking_number,timestamp,order_ref,buy...


> get_exchange_from_filename(file)
[1] "NASDAQ"

> get_date_from_filename(file)
[1] "2019-07-30 GMT"

> file
[1] "C:/NASDAQ/07302019.NASDAQ_ITCH50"

It's reading a 8.4gb unzipped file in .1 seconds.  Clearly its not trying to read it really.  
Really appreciate your help.  Started trying to build a parser from scratch, much harder than I anticipated...

**Comment by ChrisPetersen1098** [comment]
Here's the output if I force unzip from the program...

> file
[1] "C:/NASDAQ/07302019.NASDAQ_ITCH50.gz"
> count_messages(file, force_gunzip = TRUE)
[Decompressing] 'C:/NASDAQ/07302019.NASDAQ_ITCH50.gz' to '07302019.NASDAQ_ITCH50'
[Counting]   0 total messages found
[Converting] to data.table
[Done]       in 43.27 secs at 84.63MB/s
    msg_type count
 1:        S     0
 2:        R     0
 3:        H     0
 4:        Y     0
 5:        L     0
 6:        V     0
 7:        W     0
 8:        K     0
 9:        J     0
10:        h     0
11:        A     0
12:        F     0
13:        E     0
14:        C     0
15:        X     0
16:        D     0
17:        U     0
18:        P     0
19:        Q     0
20:        B     0
21:        I     0
22:        N     0
    msg_type count


It unzipped it taking 43 seconds, but still found no messages.

**Comment by DavZim** [comment]
Hi @ChrisPetersen1098,
thanks for the output. Unfortunately, I am not able to reproduce your error (see below).
Can you check that the MD5Sums are identical on your side (if not, you might have a corrupted file) and that you have the latest RITCH version installed.

``` r
# https://github.com/DavZim/RITCH/issues/28
# remotes::install_github("DavZim/RITCH")
library(RITCH)
packageVersion("RITCH")
#> [1] '0.1.11'

file <- "07302019.NASDAQ_ITCH50.gz"
tools::md5sum(c(file, gsub("\\.gz$", "", file)))
#>          07302019.NASDAQ_ITCH50.gz             07302019.NASDAQ_ITCH50 
#> "8744aba2ea125bfdde1a340ee2cea924" "3ea7eb57d1ea584b6951db42fd79bb28"

readLines(gsub("\\.gz$", ".gz.md5sum", file))
#> [1] "8744aba2ea125bfdde1a340ee2cea924 /data/apps/1/07302019.NASDAQ_ITCH50.gz"

count_messages(file)
#> [INFO] Unzipped file '07302019.NASDAQ_ITCH50' already found, using that (overwrite with force_gunzip=TRUE)
#> [Counting]   282,229,684 total messages found
#> [Converting] to data.table
#> [Done]       in 2.68 secs at 1.37GB/s
#>     msg_type     count
#>  1:        S         6
#>  2:        R      8849
#>  3:        H      8869
#>  4:        Y      8959
#>  5:        L    210706
#>  6:        V         1
#>  7:        W         0
#>  8:        K         0
#>  9:        J         2
#> 10:        h         0
#> 11:        A 124164371
#> 12:        F   1296379
#> 13:        E   7582422
#> 14:        C    135573
#> 15:        X   2358032
#> 16:        D 119999061
#> 17:        U  21253951
#> 18:        P   1461010
#> 19:        Q     17700
#> 20:        B         0
#> 21:        I   3723793
#> 22:        N         0
#>     msg_type     count

get_exchange_from_filename(file)
#> [1] "NASDAQ"

get_date_from_filename(file)
#> [1] "2019-07-30 GMT"

d <- read_trades(file)
#> [INFO] Unzipped file '07302019.NASDAQ_ITCH50' already found, using that (overwrite with force_gunzip=TRUE)
#> [Counting]   num messages 282,229,684
#> [Counting]   num 'trades' messages 1,478,710
#> [Converting] to data.table
#> [Done]       in 7.28 secs at 502.89MB/s
dplyr::glimpse(d)
#> Rows: 1,478,710
#> Columns: 14
#> $ msg_type        <chr> "P", "P", "P", "P", "P", "P", "P", "P", "P", "P", "P"…
#> $ stock_locate    <int> 6104, 1142, 1142, 4928, 14, 7928, 7928, 7928, 6104, 4…
#> $ tracking_number <int> 4, 2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,…
#> $ timestamp       <int64> 14469346417486, 14476750560883, 14489459392881, 145…
#> $ order_ref       <int64> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
#> $ buy             <lgl> TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,…
#> $ shares          <int> 52, 2, 2, 200, 190, 100, 100, 31, 100, 30, 100, 3, 10…
#> $ stock           <chr> "PFE", "BYND", "BYND", "LXRX", "AAPL", "TSLA", "TSLA"…
#> $ price           <dbl> 40.99, 193.01, 194.94, 1.84, 209.45, 234.87, 234.95, …
#> $ match_number    <int64> 17741, 17746, 17757, 17805, 17825, 17850, 17851, 17…
#> $ cross_type      <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
#> $ date            <dttm> 2019-07-30, 2019-07-30, 2019-07-30, 2019-07-30, 2019…
#> $ datetime        <int64> 2019-07-30T04:01:09.346417486+00:00, 2019-07-30T04:…
#> $ exchange        <chr> "NASDAQ", "NASDAQ", "NASDAQ", "NASDAQ", "NASDAQ", "NA…
```

<sup>Created on 2021-09-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by ChrisPetersen1098** [comment]
I just uninstalled and reinstalled RITCH and got the same error.  This is on my Windows 10 PC with R 3.6.3.  

I then installed it on my R620 server that has Debian and R 4.0.4.  The same file (not re-downloaded) could be parsed on that machine.  

If you had to guess, what would be the main difference in why my server could parse it and my PC couldn't?  R version or windows vs. Debian?

**Comment by DavZim** [comment]
Good to hear that there is nothing wrong with the package at the moment :)

It might be the case that the R version is too old. 3.6.3 vs 4.0.4 is quite a large leap. Windows vs Debian should not be a problem, though I only tested it on Ubuntu.
Maybe check your package versions as well: 

``` r
library(RITCH)

sessionInfo()
#> R version 4.0.4 (2021-02-15)
#> Platform: x86_64-pc-linux-gnu (64-bit)
#> Running under: Ubuntu 21.04
#> 
#> Matrix products: default
#> BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3
#> LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.13.so
#> 
#> locale:
#>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
#>  [3] LC_TIME=de_DE.UTF-8        LC_COLLATE=en_US.UTF-8    
#>  [5] LC_MONETARY=de_DE.UTF-8    LC_MESSAGES=en_US.UTF-8   
#>  [7] LC_PAPER=de_DE.UTF-8       LC_NAME=C                 
#>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
#> [11] LC_MEASUREMENT=de_DE.UTF-8 LC_IDENTIFICATION=C       
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] RITCH_0.1.11
#> 
#> loaded via a namespace (and not attached):
#>  [1] Rcpp_1.0.7        lattice_0.20-41   zoo_1.8-9         digest_0.6.27    
#>  [5] grid_4.0.4        magrittr_2.0.1    evaluate_0.14     highr_0.8        
#>  [9] rlang_0.4.10      stringi_1.7.3     data.table_1.14.2 rmarkdown_2.5    
#> [13] tools_4.0.4       RcppCCTZ_0.2.9    stringr_1.4.0     bit64_4.0.5      
#> [17] nanotime_0.3.3    bit_4.0.4         xfun_0.20         yaml_2.2.1       
#> [21] compiler_4.0.4    htmltools_0.5.1.1 knitr_1.30
```

<sup>Created on 2021-09-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by ChrisPetersen1098** [comment]
Really appreciate all your help.  I bet it is my R version.  I'm not ready to upgrade it yet due to some other packages, but probably will soon.  Will use it on my server.

**Comment by DavZim** [comment]
Good luck! 
You might want to look into [`qs`](https://github.com/traversc/qs) to save and load the data quickly. Eg parse the binary data on your server, save the data as a qs file, transfer the data and load it for analysis on your laptop!
Cheers

**Comment by ChrisPetersen1098** [comment]
I just bit the bullet and updated my windows machine to R 4.1.1 and didn't fix the issue.  I will just use it on Debian.  Just thought you might want to know in case others have the same issue.   Will leave the issue closed...

> sessionInfo()
R version 4.1.1 (2021-08-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] RITCH_0.1.11

loaded via a namespace (and not attached):
 [1] zoo_1.8-9         bit_4.0.4         compiler_4.1.1    tools_4.1.1       RcppCCTZ_0.2.9    Rcpp_1.0.7        remotes_2.4.0     bit64_4.0.5      
 [9] nanotime_0.3.3    grid_4.1.1        data.table_1.14.0 lattice_0.20-44 



Again, just an issue with the full NASDAQ file.  So weird that it could parse one but not the other.  I have 128GB of DDR4 ram and 16 cores on my desktop and only 92GB of DDR3 ram on my server, so not a memory or capability issue.

> file <- "F:/SharedNVME/07302019.NASDAQ_ITCH50"
> msg_count <- count_messages(file)
[Counting]   0 total messages found
[Converting] to data.table
[Done]       in 0.02 secs at 577.18GB/s
> file <- "C:/NASDAQ/20191030.BX_ITCH_50.gz"
> msg_count <- count_messages(file)
[INFO] Unzipped file 'C:/NASDAQ/20191030.BX_ITCH_50' already found, using that (overwrite with force_gunzip=TRUE)
[Counting]   29,935,874 total messages found
[Converting] to data.table
[Done]       in 0.81 secs at 501.22MB/s

**Comment by DavZim** [comment]
Maybe it has something to do with the architecture, what CPUs do you have in the machines? It might be that endianness plays a role here (though unlikely as it should work in both).
The only version difference I noticed is that your rdatatable is 0.2 versions older than mine, but that shouldnt matter.
Did you find anything else that caused the issue?
