### ISSUE TITLE
Sample file server gone/moved

### ISSUE THREAD

**Issue by stefan-jansen** [DavZim/RITCH#29]
It looks like the [FTP Server](ftp://emi.nasdaq.com/ITCH/) is gone or has moved elsewhere - any ideas if/how one could obtain samples going forward?

**Comment by DavZim** [comment]
I can confirm that the FTP server seems to be down/not available (hopefully only for the moment).
You can send me an email (see my profile->Blog->About) for further information

**Comment by DavZim** [comment]
As a note: the FTP server was migrated to an HTTPS server which can be found here: https://emi.nasdaq.com/ITCH/Nasdaq%20ITCH/

The code has been updated with 2a8bd2c
