### ISSUE TITLE
How do I extract order execution?

### ISSUE THREAD

**Issue by macdeutsche** [DavZim/RITCH#9]
Hi, David
I appreciate your code. It was very useful. 
I am wondering if you know how to extract order executed (msg_type ="E")
I tried to create my own function (it's first day of R for me), but it's giving me an error. (Error in get(name, envir = asNamespace(pkg), inherits = FALSE) : 
  object 'executed' not found)

The function that I wrote is 

``` r
executed <-function (file, start_msg_count = 0, end_msg_count = 0, buffer_size = 1e+08, 
    quiet = FALSE) 
{
    if (!file.exists(file)) 
        stop("File not found!")
    if (buffer_size < 50) 
        stop("buffer_size has to be at least 50 bytes, otherwise the messages won't fit")
    if (buffer_size > 1e+09) 
        warning("You are trying to allocate a large array on the heap, if the function crashes, try to use a smaller buffer_size")
    date_ <- get_date_from_filename(file)
    if (grepl("\\.gz$", file)) {
        if (!quiet) 
            cat(sprintf("[Extracting] from %s\n", file))
        tmp_file <- "__tmp_gzip_extract__"
        if (file.exists(tmp_file)) 
            unlink(tmp_file)
        R.utils::gunzip(filename = file, destname = tmp_file, 
            remove = F)
        file <- tmp_file
    }
    df <- RITCH:::executed(file, max(0, start_msg_count - 1), 
        max(0, end_msg_count - 1), buffer_size, quiet)
    if (file.exists("__tmp_gzip_extract__")) 
        unlink("__tmp_gzip_extract__")
    if (!quiet) 
        cat("[Formatting]\n")
    setDT(df)
    df[, `:=`(date, date_)]
    df[, `:=`(datetime, date_ + timestamp/1e+09)]
    df[msg_type == "E", `:=`(mpid = NA_character_)]
    a <- gc()
    return(df[])
}
```

**Comment by DavZim** [comment]
Do you want to only extract the `E` message type for performance reasons?
If you are OK with all modify orders messages being parsed, you can do:

``` r
file <- "MY_ITCH_FILE.BX_ITCH_50"

modifications <- get_modifications(file)

executed <- modifications[msg_type == "E"]
```

If you only want to parse the `E` message, I'll have a look at your code.

**Comment by DavZim** [comment]
As to your code:
The line `df <- RITCH:::executed(...)` won't work. R uses the `:::` to look for internal functions within the `RITCH` package. I.e., in the [get_modifications.R](https://github.com/DavZim/RITCH/blob/master/R/get_modifications.R#L50) file, it points to the `RITCH:::getModifications()` function, which is an internal C++ function, found [here](https://github.com/DavZim/RITCH/blob/master/src/getMessages.cpp#L132). As you can see, if you only want to implement the parsing of `E` messages, you would have to create your own executed-class (similar to the `Modifications` class, inheriting from the [`MessageType`](https://github.com/DavZim/RITCH/blob/master/src/MessageTypes.h)) and then you can use your r-wrapper that calls your `getExecuted()` C++ function. Lastly, you would have to rebuild the package, but that shouldn't be a problem :)

If that doesnt work, let me know.

**Comment by macdeutsche** [comment]
I appreciate it. First reply of yours would do it just fine. Silly me!

Not particularly related to your code, but would you happen to know how to convert timestamp (in nano seconds) to date and datetime?

Have one more question.

So your ITCH file is from ftp://emi.nasdaq.com/ITCH but under BX_ITCH. But there is also GIS directory. 

Right now BX_ITCH has three files, 20181228.BX_ITCH_50, 20190130.BX_ITCH_50 and 20190327.BX_ITCH_50. Looks like these are from each month end (for some reason, they forgot Feb?)

But under GIS, we have files under "Nov 18, Dec 18, Jan 19" directory
For example, they have "S122818-v50.txt", which is much bigger than 20181228.BX_ITCH_50. I downloaded both of them and compare just the msg code, and it looks like S122818-v50.txt is much more comprehensive.  Do you know which one to use?

BTW, my name is Seunghan Nam and I recently started to work on ITCH, so very limited. I am in a school, NYIT in new york (accounting). Good luck with studies by the way.

**Comment by DavZim** [comment]
Thanks and glad that I could help Seunghan. :)

1 Nanosecond is 1 billionth of a second. Thus you can use the following:

``` r
nano_to_hms <- function(x) {
  hms::hms(seconds = x / 1e9)
}

x <- 1e9 * 3600 * 12 + # 12 hours
  1e9 * 60 * 34 +      # 35 minutes
  1e9 * 12.123         # 12.123 seconds

nano_to_hms(x)
#> 12:34:12.123
```

<sup>Created on 2019-04-16 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Regarding the files, the `xxx_ITCH_50` files are highly compressed, thus comparing them to .txt files does not work.
Having said that, I haven't looked at them, so I am not sure what they are exactly. If you found them to be better, can you give a quick reply.

**Comment by macdeutsche** [comment]
My coauthor contacted NASDAQ and if we hear from them, I will respond.
